twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/layout.html.twig'
    globals:
        app_company: Prodeimat
        app_email: Prodeimat
when@test:
    twig:
        strict_variables: true
